# Generated by Django 3.0.3 on 2020-03-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0004_auto_20200315_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_link',
            field=models.CharField(default='User', max_length=30),
        ),
    ]
