# Generated by Django 3.0.3 on 2020-03-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0005_projects_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_link',
            field=models.CharField(default='User', max_length=600),
        ),
    ]
