# Generated by Django 3.0.3 on 2020-03-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0009_auto_20200315_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='profile_id',
        ),
    ]
