# Generated by Django 3.0.3 on 2020-03-15 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0010_remove_projects_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awardsapp.Profile'),
        ),
    ]
