# Generated by Django 3.0.3 on 2020-03-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0017_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='option_eight',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_eight_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_five',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_five_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_four',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_four_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_nine',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_nine_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_seven',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_seven_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_six',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_six_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_ten',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_ten_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_one',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_three',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_two',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
